# Generated by Django 5.0.4 on 2024-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('districtid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('districtname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('locationname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=50)),
            ],
        ),
       
        
    ]
