# Generated by Django 5.0.4 on 2024-05-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_cart_category_contact_cusdesign_cusregform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
