# Generated by Django 5.0.4 on 2024-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
