# Generated by Django 5.0.4 on 2024-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_alter_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_address',
            fields=[
                ('billing_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('Pincode', models.BigIntegerField(blank=True, null=True)),
                ('City', models.CharField(max_length=100)),
                ('State', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
