# Generated by Django 5.0.4 on 2024-05-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0011_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_address',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='Pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='billing_address',
            old_name='Street',
            new_name='street',
        ),
    ]
