# Generated by Django 5.0.4 on 2024-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0013_billing_address_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_master',
            fields=[
                ('order_master_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField()),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
    ]
