# Generated by Django 5.0.4 on 2024-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0014_order_detail_order_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.BigIntegerField(blank=True, null=True)),
                ('card_no', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('paid_date', models.DateField()),
                ('paid_status', models.CharField(max_length=100)),
            ],
        ),
    ]
