# Generated by Django 5.0.4 on 2024-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0017_order_detail_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_master',
            name='payment_method',
            field=models.CharField(default='', max_length=50, verbose_name=''),
            preserve_default=False,
        ),
    ]
